theme: jekyll-theme-cayman

plugins:
  - jekyll-redirect-from

title: Ametrine Development
description: Images, scripts and solutions to common issues we encounter in the Genius Bar of the r/Jailbreak discord server
google_analytics: UA-168687465-1
